### ISSUE TITLE
又来提建议啦

### ISSUE THREAD

**Issue by caspershw** [touchitvoid/wanna#5]
- 可以给主页文章标题加上<a>标签
- 主页文章的框框也可以加上 border-radius
- Pad会出现排版错误的问题 
[![pad.jpg](https://i.loli.net/2018/05/06/5aeef046a4eca.jpg)](https://i.loli.net/2018/05/06/5aeef046a4eca.jpg)
- 小屏幕设备标题会换行溢出  
[![s5.jpg](https://i.loli.net/2018/05/06/5aeef0d561990.jpg)](https://i.loli.net/2018/05/06/5aeef0d561990.jpg)

**Comment by caspershw** [comment]
这个主题真的是看到第一眼就很喜欢的那种，有空了一定多来提建议（逃

**Comment by touchitvoid** [comment]
qwq,今天对你说的文件做了整理，顺带调小了评论大小，加上了pjax，等下也把你这些bug给处理掉...晚些push到gayhub

**Comment by caspershw** [comment]
dalao厉害了，不是很会前端，只能偶尔提提建议了。。。

- 赞赏弹出来的图好像太大了。。不完整
- 评论感觉小了有点不和谐。。如果把宽度调回来，再改一改样式，不知道会不会好一些。。
就像这样
![comm.jpg](https://i.loli.net/2018/05/09/5af1d3c978211.jpg)

刚看到，祝dalao生日快乐

**Comment by touchitvoid** [comment]
ok，今天我调整看看，(•‾⌣‾•)y谢祝福

**Comment by caspershw** [comment]
那啥感觉评论框没对齐。。有点歪。。那个赞赏码我这看到还是不完整。。加一个width: 400px 就可以显示完整了。

**Comment by touchitvoid** [comment]
赞赏码我改过了应该是ok的？

**Comment by caspershw** [comment]
我这好像还是不行。。
![2.jpg](https://i.loli.net/2018/05/19/5affd4262332d.jpg)
![1.jpg](https://i.loli.net/2018/05/19/5affd426268d1.jpg)

**Comment by touchitvoid** [comment]
我只是忘了传到我博客....git上是更新了的
